name: Workflow of exercise 3
run-name: Exercise 3

# Events triggering the workflow
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    MyVariable: "Hello World"

# Group of jobs to run as part of the workflow
jobs:
    job_job:
        env:
            JobVariable: "this is my job variable"
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ env.MyVariable }}"
            - run: echo "${{ env.JobVariable }}"
            - name: github.action evaluated
              run: echo "${{ github.action }}"
            - name: GITHUB_TOKEN
              run: echo "${{ github.token }}"
            - name: GITHUB_TOKEN using bash syntax
              run: echo "${ GITHUB_TOKEN }"
            - name: MY_SECRET_NAME
              run: echo "${{ secrets.MY_SECRET_NAME }}"
    check_secret_job:
        runs-on: ubuntu-latest
        outputs:
            should_run: ${{ steps.check_secret.outputs.should_run }}
        steps:
            - id: check_secret
              run: |
                    if [[ "${{ secrets.MY_SECRET_NAME }}" == "MY_SECRET_NAME" ]]; then
                        echo "should_run=true" >> "$GITHUB_OUTPUT"
                    else
                        echo "should_run=false" >> "$GITHUB_OUTPUT"
                    fi

    conditional_job:
        needs: check_secret_job
        if: ${{ needs.check_secret_job.outputs.should_run == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - run: echo "Secret matched expected value, running conditional_job"